name: Test React.js Site

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run type-check

      - name: Build React app
        run: npm run build